version: '3.9'

services:
  web:
    build: .
    container_name: lab3-web
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html

  db:
    image: mysql:8.0
    container_name: lab3-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab3db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
